### ISSUE TITLE
Replace <? extends Throwable> with <? extends Exception>

### ISSUE THREAD

**Issue by pivovarit** [pivovarit/ThrowingFunction#15]
Everywhere

**Comment by brunoabdon** [comment]
Why, @pivovarit ?

**Comment by pivovarit** [comment]
Let's see Error's documentation:

> An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch.

**Comment by brunoabdon** [comment]
Makes sense.
It would be break compatibility, though.

**Comment by pivovarit** [comment]
Yes, so this could happen only with a major release
